### PR TITLE
added index

### PR DESCRIPTION
**Pull request by tom-fitz**

### CODE REVIEW

**Comment by tom-fitz** [comment]
Need review/help.

Image cannot seem to be targeted and allow for the text input to be changed. I also don't believe that an image was required but guess what, it's there and now there is now turning back. Everything else seems to be working o.k.

**Comment by morecallan** [comment]
@basictom - You're close on this. You can get the input text to change if the image is clicked on by traversing the parentNode (just like you did to add the border to the card) and then editing selectDesc to traverse back down to the correct childNode. 

Also make sure that your README has all the components we talked about: how to run, etc.

**Comment by tom-fitz** [comment]
Added to README.md. Also added a function to clear the input field on the enter key, but it also clears the description - womp womp.

**Comment by tom-fitz** [comment]
Added the bootstrap row feature. Should be all set now, i'll let you be the judge. 

@morecallan I am assuming I need approval to merge?

**Comment by zoeames** [comment]
@basictom The code looks fine but your Readme needs more work.  Take the instructions out of there - they appear in instructions.md.  At minimum your readme should have:  screenshot(s), description, instructions for how to run (you have this but the formatting could be better)

**Comment by tom-fitz** [comment]
@zoeames Hey Zoe, I added a pretty and descriptive readme.

**Comment by zoeames** [comment]
Your readme is funny but it makes you look like a tool.  Fix it so a future employer doesn't think you are a tool.

**Comment by tom-fitz** [comment]
Fixed.

**Comment by rousell** [comment]
@basictom ok this is good. completing PR.

**Pull request merged**
